### ISSUE TITLE
add beta distribution

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/go-statistics#7]
In order to support exploration of uncertainty around damage functions using the beta distribution we need to add the beta to go-statisitics.

Much like the shifted gamma https://github.com/HydrologicEngineeringCenter/go-statistics/blob/master/statistics/shiftedgammaDistribution.go we will want to rely on an external statistics package to do the heavy lifting.
The gonum project has the beta distribution in the distuv package. I believe it will form an excellent starting place. 
https://github.com/gonum/gonum/blob/master/stat/distuv/beta.go

implement the base BetaDistribution, we will investigate the need for beta4 after we have the beta implemented.

**Comment by rnugent3** [comment]
What is the role of:

`json:"alpha"`

inside the shifted gamma struct? 

Also - can I follow any guide I find online about using docker together with VS, or are there specific things I need to know? I don’t have access to my personal computer right now.

**Comment by HenryGeorgist** [comment]
`json:"alpha"` is the syntax to define how serialization to json would work. If we wanted to seralize to a json object it would be as simple as calling json.Marshal(<some instance of shifted>) and json.Unmarshal([]bytes) - since ShiftedGamma implements the interface ContinuousDistribution, and my references of it in go-consequences are through the interface, json marshal and unmarshal becomes complicated unfortunately. I was exploring a handy way to unwrap the json and build the proper distribution, but i have not finished that development item yet. 

I dont have a good tutorial, the help online is pretty easy to google, but i have struggled with it personally - if you want, give me an invite on my calendar today and i will walk you through it.
My guess is the first problem you will have is setting up the workspace sharing under Docker Desktop Dashboard > settings > file sharing. Map a folder to the directory for go-statistics before you try to build that image.
